### ISSUE TITLE
Create your Amazon Web Service account

### ISSUE THREAD

**Issue by mmedlin1997** [PresidentDwayneCamacho/Corner#15]
Team, the Bronco Corner domain name is registered, and hosted through AWS now.
The server will live in a 'bucket' called broncocorner.com hosted by AWS.
I set up a group 'camacho', so you can work on the live website. 

Please create your own AWS accounts to access this group. 
Steps to do this:
1.  Create your AWS account.
2.  Get your AWS account number: AWS→ Support Tab→ Support Center→upper right-hand corner
3.  Log in on your sign-in page (modify the web address to use your account). Temp password is admin.
https://< your-acct-number >.signin.aws.amazon.com/console

**Comment by mmedlin1997** [comment]
broncocorner.com is live.
I used a static html page for now just to verify everything works.

**Comment by TreyAmador** [comment]
Wow, so exciting.  How much did this cost?

________________________________

**Comment by tried42long** [comment]
Nice, Mark!
